# Generated by Django 5.2.8 on 2025-11-24 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DniTygodnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=45)),
                ('Numer', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Dni Tygodnia',
            },
        ),
        migrations.CreateModel(
            name='GodzinyLekcyjne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numer', models.IntegerField()),
                ('CzasOd', models.TimeField(max_length=45)),
                ('CzasDo', models.TimeField(max_length=45)),
                ('CzasTrwania', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Godziny Lekcyjne',
            },
        ),
        migrations.CreateModel(
            name='PlanWpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien_tygodnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.dnitygodnia')),
                ('godzina_lekcyjna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.godzinylekcyjne')),
            ],
            options={
                'verbose_name_plural': 'Wpisy do Planu',
            },
        ),
        migrations.CreateModel(
            name='PlanyZajec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObowiazujeOdDnia', models.DateField()),
                ('wpisy', models.ManyToManyField(blank=True, related_name='plany_zajec', to='timetables.planwpis')),
            ],
            options={
                'verbose_name_plural': 'Plany Zajęć',
            },
        ),
        migrations.CreateModel(
            name='Zajecia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nauczyciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zajecia_nauczyciela', to='users.nauczyciel')),
            ],
            options={
                'verbose_name_plural': 'Zajęcia',
            },
        ),
        migrations.AddField(
            model_name='planwpis',
            name='zajecia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.zajecia'),
        ),
    ]
