# Generated by Django 5.2.8 on 2025-11-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
        ('users', '0002_adres_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('data', models.DateTimeField()),
                ('nauczyciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wydarzenia', to='users.nauczyciel')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['-data'],
            },
        ),
    ]
