# Generated by Django 5.2.8 on 2025-11-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0001_initial'),
        ('users', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planyzajec',
            name='klasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plany_zajec', to='users.klasa'),
        ),
        migrations.AddField(
            model_name='planyzajec',
            name='wpisy',
            field=models.ManyToManyField(blank=True, related_name='plany_zajec', to='timetables.planwpis'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='klasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wydarzenia', to='users.klasa'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='nauczyciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wydarzenia', to='users.nauczyciel'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='przedmiot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wydarzenia', to='utils.przedmiot'),
        ),
        migrations.AddField(
            model_name='zajecia',
            name='nauczyciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zajecia_nauczyciela', to='users.nauczyciel'),
        ),
        migrations.AddField(
            model_name='zajecia',
            name='przedmiot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zajecia_przedmiotu', to='utils.przedmiot'),
        ),
        migrations.AddField(
            model_name='planwpis',
            name='zajecia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.zajecia'),
        ),
    ]
