# Generated by Django 5.2.8 on 2026-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='calodobowe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='godzina_do',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='godzina_od',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='data',
            field=models.DateField(),
        ),
    ]
