# Generated by Django 5.2.8 on 2025-11-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_wydarzenie'),
        ('users', '0003_uczen_adres_uczen_klasa'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planyzajec',
            name='klasa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plany_zajec', to='users.klasa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zajecia',
            name='przedmiot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zajecia_przedmiotu', to='utils.przedmiot'),
            preserve_default=False,
        ),
    ]
