# Generated by Django 5.2.8 on 2025-11-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_planyzajec_klasa_zajecia_przedmiot'),
        ('users', '0003_uczen_adres_uczen_klasa'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='klasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wydarzenia', to='users.klasa'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='przedmiot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wydarzenia', to='utils.przedmiot'),
        ),
    ]
