# Generated by Django 5.2.8 on 2025-11-25 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(blank=True, max_length=200, null=True)),
                ('numer_domu', models.CharField(blank=True, max_length=50, null=True)),
                ('numer_mieszkania', models.CharField(blank=True, max_length=50, null=True)),
                ('miasto', models.CharField(blank=True, max_length=100, null=True)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=20, null=True)),
                ('kraj', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Whether TOTP 2FA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32 secret used for TOTP with Google Authenticator', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='Choose your preferred theme', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=10, null=True)),
                ('numer', models.IntegerField(blank=True, null=True)),
                ('wychowawca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prowadzone_klasy', to='users.nauczyciel')),
            ],
            options={
                'verbose_name': 'Klasa',
                'verbose_name_plural': 'Klasy',
            },
        ),
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przeczytana', models.BooleanField(default=False)),
                ('temat', models.CharField(max_length=255)),
                ('tresc', models.TextField()),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wyslane_wiadomosci', to=settings.AUTH_USER_MODEL)),
                ('odbiorca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odebrane_wiadomosci', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['-data_wyslania'],
            },
        ),
    ]
