# Generated by Django 5.2.8 on 2026-03-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodzic',
            options={'verbose_name': 'Rodzic', 'verbose_name_plural': 'Rodzice'},
        ),
    ]
