# Generated by Django 5.2.8 on 2025-11-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adres_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczen',
            name='adres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adres'),
        ),
        migrations.AddField(
            model_name='uczen',
            name='klasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uczniowie', to='users.klasa'),
        ),
    ]
