# Generated by Django 5.2.8 on 2025-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=3)),
                ('waga', models.PositiveSmallIntegerField(default=1)),
                ('opis', models.CharField(blank=True, max_length=200, null=True)),
                ('data_wystawienia', models.DateTimeField(auto_now_add=True)),
                ('czy_punkty', models.BooleanField(default=False)),
                ('czy_opisowa', models.BooleanField(default=False)),
                ('czy_do_sredniej', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ocena',
                'verbose_name_plural': 'Oceny',
                'ordering': ['-data_wystawienia'],
            },
        ),
        migrations.CreateModel(
            name='OcenaKoncowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'Ocena końcowa',
                'verbose_name_plural': 'Oceny końcowe',
            },
        ),
        migrations.CreateModel(
            name='OcenaOkresowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=3)),
                ('okres', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ocena okresowa',
                'verbose_name_plural': 'Oceny okresowe',
            },
        ),
        migrations.CreateModel(
            name='ZachowaniePunkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkty', models.IntegerField()),
                ('opis', models.TextField(blank=True, null=True)),
                ('data_wpisu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Punkt z zachowania',
                'verbose_name_plural': 'Punkty z zachowania',
                'ordering': ['-data_wpisu'],
            },
        ),
    ]
