# Generated by Django 5.2.8 on 2025-11-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=3)),
                ('waga', models.PositiveSmallIntegerField(default=1)),
                ('opis', models.CharField(blank=True, max_length=200, null=True)),
                ('data_wystawienia', models.DateTimeField(auto_now_add=True)),
                ('czy_punkty', models.BooleanField(default=False)),
                ('czy_opisowa', models.BooleanField(default=False)),
                ('czy_do_sredniej', models.BooleanField(default=True)),
                ('nauczyciel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wystawione_oceny', to='users.nauczyciel')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='users.uczen')),
            ],
            options={
                'verbose_name': 'Ocena',
                'verbose_name_plural': 'Oceny',
                'ordering': ['-data_wystawienia'],
            },
        ),
        migrations.CreateModel(
            name='OcenaKoncowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nauczyciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nauczyciel')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny_koncowe', to='users.uczen')),
            ],
            options={
                'verbose_name': 'Ocena końcowa',
                'verbose_name_plural': 'Oceny końcowe',
            },
        ),
        migrations.CreateModel(
            name='OcenaOkresowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=3)),
                ('okres', models.IntegerField()),
                ('nauczyciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nauczyciel')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny_okresowe', to='users.uczen')),
            ],
            options={
                'verbose_name': 'Ocena okresowa',
                'verbose_name_plural': 'Oceny okresowe',
            },
        ),
    ]
