# Generated by Django 5.2.8 on 2025-11-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('users', '0002_adres_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZachowaniePunkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkty', models.IntegerField()),
                ('opis', models.TextField(blank=True, null=True)),
                ('data_wpisu', models.DateTimeField(auto_now_add=True)),
                ('nauczyciel_wpisujacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpisane_punkty_zachowania', to='users.nauczyciel')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkty_zachowania', to='users.uczen')),
            ],
            options={
                'verbose_name': 'Punkt z zachowania',
                'verbose_name_plural': 'Punkty z zachowania',
                'ordering': ['-data_wpisu'],
            },
        ),
    ]
