# Generated by Django 5.2.8 on 2025-11-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('users', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='nauczyciel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wystawione_oceny', to='users.nauczyciel'),
        ),
        migrations.AddField(
            model_name='ocena',
            name='przedmiot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='utils.przedmiot'),
        ),
        migrations.AddField(
            model_name='ocena',
            name='uczen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='users.uczen'),
        ),
        migrations.AddField(
            model_name='ocenakoncowa',
            name='nauczyciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nauczyciel'),
        ),
        migrations.AddField(
            model_name='ocenakoncowa',
            name='przedmiot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny_koncowe', to='utils.przedmiot'),
        ),
        migrations.AddField(
            model_name='ocenakoncowa',
            name='uczen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny_koncowe', to='users.uczen'),
        ),
        migrations.AddField(
            model_name='ocenaokresowa',
            name='nauczyciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nauczyciel'),
        ),
        migrations.AddField(
            model_name='ocenaokresowa',
            name='przedmiot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oceny_okresowe', to='utils.przedmiot'),
        ),
        migrations.AddField(
            model_name='ocenaokresowa',
            name='uczen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny_okresowe', to='users.uczen'),
        ),
        migrations.AddField(
            model_name='zachowaniepunkty',
            name='nauczyciel_wpisujacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpisane_punkty_zachowania', to='users.nauczyciel'),
        ),
        migrations.AddField(
            model_name='zachowaniepunkty',
            name='uczen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkty_zachowania', to='users.uczen'),
        ),
    ]
