# Generated by Django 5.2.8 on 2026-03-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
        ('users', '0002_alter_rodzic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena',
            name='nauczyciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wystawione_oceny', to='users.nauczyciel'),
        ),
    ]
