# Generated by Django 5.2.8 on 2025-11-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_ocena_przedmiot'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocenakoncowa',
            name='przedmiot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='oceny_koncowe', to='utils.przedmiot'),
            preserve_default=False,
        ),
    ]
