# Generated by Django 5.2.8 on 2025-11-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_ocenakoncowa_przedmiot'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocenaokresowa',
            name='przedmiot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oceny_okresowe', to='utils.przedmiot'),
        ),
    ]
