# Generated by Django 5.2.8 on 2025-11-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_source', models.CharField(choices=[('local', 'Local'), ('external', 'External')], default='local', max_length=20)),
                ('last_import_file', models.CharField(blank=True, max_length=255, null=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('nazwa_skrocona', models.CharField(blank=True, max_length=50, null=True)),
                ('numer', models.IntegerField(blank=True, null=True)),
                ('czy_dodatkowy', models.BooleanField(default=False)),
                ('nauczyciele', models.ManyToManyField(blank=True, related_name='przedmioty', to='users.nauczyciel')),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
            },
        ),
        migrations.CreateModel(
            name='PracaDomowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('data_wystawienia', models.DateTimeField(auto_now_add=True)),
                ('termin', models.DateField()),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prace_domowe', to='users.klasa')),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prace_domowe', to='users.nauczyciel')),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prace_domowe', to='utils.przedmiot')),
            ],
            options={
                'verbose_name': 'Praca domowa',
                'verbose_name_plural': 'Prace domowe',
                'ordering': ['-data_wystawienia'],
            },
        ),
        migrations.CreateModel(
            name='Temat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('numer_lekcji', models.IntegerField(blank=True, null=True)),
                ('czas_realizacji', models.IntegerField(blank=True, help_text='Czas realizacji w minutach', null=True)),
                ('czas_od', models.TimeField(blank=True, null=True)),
                ('czas_do', models.TimeField(blank=True, null=True)),
                ('nauczyciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nauczyciel')),
                ('przedmiot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.przedmiot')),
            ],
        ),
    ]
