# Generated by Django 5.2.8 on 2025-11-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusyObecnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wartosc', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Statusy Obecności',
            },
        ),
        migrations.CreateModel(
            name='Frekwencja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('godzina_lekcyjna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetables.godzinylekcyjne')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frekwencja', to='users.uczen')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frekwencja', to='attendance.statusyobecnosci')),
            ],
            options={
                'verbose_name_plural': 'Frekwencja',
            },
        ),
    ]
