# Generated by Django 5.2.8 on 2025-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frekwencja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Frekwencja',
            },
        ),
        migrations.CreateModel(
            name='StatusyObecnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wartosc', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Statusy Obecności',
            },
        ),
    ]
