# Generated by Django 5.2.8 on 2025-11-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frekwencja',
            name='godzina_lekcyjna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetables.godzinylekcyjne'),
        ),
    ]
